sudo: required

services:
  - mysql
env:
  global:
    # - DOCKER_COMPOSE_VERSION=1.25.4
    # - APP_PORT=80
    # - MYSQL_ROOT_PASSWORD=1234
    # - MYSQL_USER=user
    # - MYSQL_PASSWORD=1234
    # - MYSQL_DATABASE=db_assign
    # - APP_DEV_MYSQL_PORT=3306
    - TYPEORM_CONNECTION=mysql
    - TYPEORM_HOST=localhost
    - TYPEORM_PORT=3306
    - TYPEORM_USERNAME=travis
    - TYPEORM_PASSWORD=
    - TYPEORM_DATABASE=db_assign
  
language: node_js

node_js:
  - "10"

# before_cache:
#   # Save tagged docker images
#   - >
#     mkdir -p $HOME/docker && docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}} {{.ID}}'
#     | xargs -n 2 -t sh -c 'test -e $HOME/docker/$1.tar.gz || docker save $0 | gzip -2 > $HOME/docker/$1.tar.gz'
    
cache:
  bundler: true
  yarn: true
  directories:
    # - $HOME/docker
    - $HOME/.npm

# addons:
#   sauce_connect: true
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS db_assign;'
  - mysql -e "SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''));"
  # Instal yarn
  # - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version version-number
  # - export PATH="$HOME/.yarn/bin:$PATH"
  # install express
  - cd app &&  yarn --frozen-lockfile && cd ..    
    # Load cached docker images
  - if [[ -d $HOME/docker ]]; then ls $HOME/docker/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load"; fi
  
# addons:
#   apt:
#     packages:
#       - docker-ce

before_script:
  # - docker -v
  # - docker-compose --version
  # - docker-compose -f docker-compose-test.yml up -d  --build
  # - docker ps -a
  # - sleep 30  # wait for MariaDB to start
  # - docker ps -a
  - sudo chmod +x ./script-travis.sh

script: 
  - yarn db:sync
  - yarn test
  - yarn build # check code again
  # - ./script-travis.sh

after_script:
  - docker-compose   down
  - docker-compose -f docker-compose-test.yml down