version: '3.5'


networks:
  backend_network:
    name: type_api
    driver: bridge

services:
  nginx:
    image: nginx:alpine
    container_name: type_app_nginx
    volumes:
      - ./nginx:/etc/nginx/
    ports:
      - $APP_PORT:80
    links:
      - backend_app:app
    networks: 
      - backend_network
  backend_app:
    container_name: type_app
    image: keymetrics/pm2:10-alpine
    # restart: always
    working_dir: /mnt/app  
    command: > 
        sh -c "pm2-runtime start /mnt/app/linux.config.js --env production"
    env_file:
      - ./.env
    environment:
      - NODE_ENV=production
      - TYPEORM_PORT=3306
      - TYPEORM_HOST=192.168.99.1
    volumes:
      - ./app:/mnt/app
    networks: 
      - backend_network

  
  mysql:
    container_name: type_db
    image: mysql:5.7.29
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      TZ: Asia/Bangkok
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--innodb-flush-method=fsync']
    ports:
      - $APP_DEV_MYSQL_PORT:3306
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks: 
      - backend_network

volumes: 
  mysqldata: {}